import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
//
import { Providers } from "./providers";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="es" className="light">
      <body
        className={`antialiased ${montserrat.className}`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
